/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Soldier.glb
*/

/* 
si quieres agregar otro modelos corre esto: npx gltfjsx [Model.glb]
para generar la plantilla base del modelo automaticamente 
despues la modificas o comfiguras como quieras
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Soldier_model(props) {

  const group = useRef()

  const { nodes, materials, animations } = useGLTF('./models/soldier/Soldier.glb')//aqui esta la data del modelo

  const { actions } = useAnimations(animations, group) //aqui estas las animaciones del modelo

  return (
    /* aqui se construlle el modelo con los datos optenidos antes */
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Character" rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="vanguard_Mesh" geometry={nodes.vanguard_Mesh.geometry} material={materials.VanguardBodyMat} skeleton={nodes.vanguard_Mesh.skeleton} />
          <skinnedMesh name="vanguard_visor" geometry={nodes.vanguard_visor.geometry} material={materials.Vanguard_VisorMat} skeleton={nodes.vanguard_visor.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/soldier/Soldier.glb')//pre carga del modelo

export default Soldier_model
