/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 .\castle.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Castillo_model(props) {
  const { nodes, materials } = useGLTF('./models/castillo/castle.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[0, -8.014, 0]} />
      <group position={[1.608, 0.067, -16.916]}>
        <group position={[-1.608, -0.067, 16.916]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.Mesh021.geometry} material={materials.TX_Trims} />
          <mesh geometry={nodes.Mesh021_1.geometry} material={materials.TX_TP1} />
          <mesh geometry={nodes.Mesh021_2.geometry} material={materials.TX_Water} />
        </group>
        <group position={[-1.608, -0.067, 16.916]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.Mesh028.geometry} material={materials.TX_Grass} />
          <mesh geometry={nodes.Mesh028_1.geometry} material={materials.TX_Trims} />
        </group>
        <group position={[-1.608, -0.067, 16.915]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.Mesh036.geometry} material={materials.TX_Wood} />
          <mesh geometry={nodes.Mesh036_1.geometry} material={materials.TX_Roof} />
        </group>
        <group position={[-1.608, -0.067, 16.916]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.Mesh043.geometry} material={materials.TX_Wood} />
          <mesh geometry={nodes.Mesh043_1.geometry} material={materials.TX_Castle_Foliage} />
        </group>
        <mesh geometry={nodes.Bush.geometry} material={materials.TX_Castle_Foliage} position={[-1.608, -0.067, 16.915]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.Castle_Gate.geometry} material={materials.TX_Wood} position={[-1.608, -0.067, 16.915]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.Chair6.geometry} material={materials.TX_Wood} position={[10.392, 0.363, -103.884]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh geometry={nodes.Chair1.geometry} material={materials.TX_Wood} position={[25.192, 0.363, -63.384]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
        <mesh geometry={nodes.Chair8.geometry} material={materials.TX_Wood} position={[-18.808, 0.363, -109.084]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
        <mesh geometry={nodes.Chair2.geometry} material={materials.TX_Wood} position={[25.192, 0.363, -65.184]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
        <mesh geometry={nodes.Chair3.geometry} material={materials.TX_Wood} position={[25.192, 0.363, -74.584]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
        <mesh geometry={nodes.Chair4.geometry} material={materials.TX_Wood} position={[10.392, 0.363, -98.084]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh geometry={nodes.Chair5.geometry} material={materials.TX_Wood} position={[10.392, 0.363, -100.084]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh geometry={nodes.Chair7.geometry} material={materials.TX_Wood} position={[-18.808, 0.363, -113.084]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
        <mesh geometry={nodes.Bassin.geometry} material={materials.TX_Wood} position={[-1.608, -0.067, 16.915]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.Barrel.geometry} material={materials.TX_Wood} position={[-1.608, -0.067, 16.915]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.Fence.geometry} material={materials.TX_Wood} position={[-1.608, -0.067, 16.916]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.Ladder.geometry} material={materials.TX_Wood} position={[-1.608, -0.067, 16.915]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.Crate.geometry} material={materials.TX_Wood} position={[-1.608, -0.067, 16.916]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.Lightpost.geometry} material={materials.TX_Wood} position={[-1.608, -0.067, 16.916]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.Grass.geometry} material={materials.TX_Castle_Foliage} position={[-1.608, -0.067, 16.915]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.Logs.geometry} material={materials.TX_Castle_Foliage} position={[-1.608, -0.067, 16.915]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.Flower.geometry} material={materials.TX_Castle_Foliage} position={[-1.608, -0.067, 16.916]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.Pont_Levis.geometry} material={materials.TX_Wood} position={[-1.608, -0.067, 16.916]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.Scaffolding.geometry} material={materials.TX_Wood} position={[-1.608, -0.067, 16.916]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.Table.geometry} material={materials.TX_Wood} position={[-1.608, -0.067, 16.916]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.TeleportFloor1.geometry} material={materials.TX_TP1} position={[-1.608, -0.067, 16.916]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.TeleportFloor2.geometry} material={materials.TX_TP1} position={[-1.608, -0.067, 16.916]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.Rock.geometry} material={materials.TX_Rock} position={[-1.608, -0.067, 16.916]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.TeleportFloor4.geometry} material={materials.TX_Wood} position={[-1.608, -0.067, 16.916]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.TeleportFloor5.geometry} material={materials.TX_TP1} position={[-1.608, -0.067, 16.916]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.TeleportFloor3.geometry} material={materials.TX_Trims} position={[-1.608, -0.067, 16.915]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.TeleportFloor6.geometry} material={materials.TX_Trims} position={[-1.608, -0.067, 16.916]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.TeleportFloor7.geometry} material={materials.TX_Trims} position={[-1.608, -0.067, 16.915]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.VaseB.geometry} material={materials.TX_Wood} position={[-1.608, -0.067, 16.915]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.VaseA.geometry} material={materials.TX_Wood} position={[-1.608, -0.067, 16.916]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.VaseC.geometry} material={materials.TX_Wood} position={[-1.608, -0.067, 16.915]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.Water.geometry} material={materials.TX_Water} position={[-1.608, -0.067, 16.916]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.Tree.geometry} material={materials.TX_Castle_Foliage} position={[-1.608, -0.067, 16.915]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.Statue.geometry} material={materials.TX_Eagle} position={[-1.608, -0.067, 16.916]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh011.geometry} material={materials.TX_Castle_Wall} />
        <mesh geometry={nodes.Mesh011_1.geometry} material={materials.TX_Trims} />
        <mesh geometry={nodes.Mesh011_2.geometry} material={materials.TX_TP1} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group position={[0, -0.085, -0.005]}>
          <mesh geometry={nodes.Mesh017.geometry} material={materials.TX_Roof} />
          <mesh geometry={nodes.Mesh017_1.geometry} material={materials.TX_Wood} />
        </group>
        <group position={[0.001, -0.074, 0.016]}>
          <mesh geometry={nodes.Mesh013.geometry} material={materials.TX_Wood} />
          <mesh geometry={nodes.Mesh013_1.geometry} material={materials.TX_Roof} />
        </group>
        <group position={[-0.002, -0.054, -0.007]}>
          <mesh geometry={nodes.Mesh016.geometry} material={materials.TX_Trims} />
          <mesh geometry={nodes.Mesh016_1.geometry} material={materials.TX_Castle_Wall} />
        </group>
        <group position={[0, -0.089, 0]}>
          <mesh geometry={nodes.Mesh015.geometry} material={materials.TX_Wood} />
          <mesh geometry={nodes.Mesh015_1.geometry} material={materials.TX_Castle_Wall} />
        </group>
        <mesh geometry={nodes.Mesh012.geometry} material={materials.TX_Trims} />
        <mesh geometry={nodes.Mesh012_1.geometry} material={materials.TX_Castle_Wall} />
        <mesh geometry={nodes.Mesh012_2.geometry} material={materials.TX_Wood} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh008.geometry} material={materials.TX_Castle_Banners} />
        <mesh geometry={nodes.Mesh008_1.geometry} material={materials.TX_Wood} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh010.geometry} material={materials.TX_Castle_Wall} />
        <mesh geometry={nodes.Mesh010_1.geometry} material={materials.TX_Trims} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh018.geometry} material={materials.TX_Roof} />
        <mesh geometry={nodes.Mesh018_1.geometry} material={materials.TX_Wood} />
        <mesh geometry={nodes.Mesh018_2.geometry} material={materials.TX_Trims} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh014.geometry} material={materials.TX_Trims} />
        <mesh geometry={nodes.Mesh014_1.geometry} material={materials.TX_Castle_Wall} />
        <mesh geometry={nodes.Mesh014_2.geometry} material={materials.TX_Roof} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh024.geometry} material={materials.TX_Wood} />
        <mesh geometry={nodes.Mesh024_1.geometry} material={materials.TX_Roof} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh026.geometry} material={materials.TX_Castle_Wall} />
        <mesh geometry={nodes.Mesh026_1.geometry} material={materials.TX_Trims} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh027.geometry} material={materials.TX_Roof} />
        <mesh geometry={nodes.Mesh027_1.geometry} material={materials.TX_Wood} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh025.geometry} material={materials.TX_Trims} />
        <mesh geometry={nodes.Mesh025_1.geometry} material={materials.TX_Castle_Wall} />
      </group>
      <mesh geometry={nodes.Sign.geometry} material={materials.TX_Wood} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Wall_Plant.geometry} material={materials.TX_Castle_Foliage} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <group position={[-0.539, 4.002, -67.662]}>
        <group position={[0.539, 5.418, 3.128]} rotation={[Math.PI / 2, 0, 0]} scale={0.4}>
          <mesh geometry={nodes.Mesh080.geometry} material={materials.TX_Atlas8H_3} />
          <mesh geometry={nodes.Mesh080_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[12.842, -2.677, 59.092]} rotation={[1.276, 0, 0]} scale={0.25}>
          <mesh geometry={nodes.Mesh073.geometry} material={materials.TX_Atlas8H_2} />
          <mesh geometry={nodes.Mesh073_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[8.193, -2.757, -17.124]} rotation={[Math.PI / 2, 0, 0]} scale={0.2}>
          <mesh geometry={nodes.Mesh097.geometry} material={materials.TX_Atlas8H_1} />
          <mesh geometry={nodes.Mesh097_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[-16.277, 1.141, -20.607]} rotation={[Math.PI / 2, 0, 0]} scale={0.2}>
          <mesh geometry={nodes.Mesh090.geometry} material={materials.TX_Atlas8H_4} />
          <mesh geometry={nodes.Mesh090_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[31.174, 1.674, -33.752]} rotation={[Math.PI / 2, 0, 0.115]} scale={0.25}>
          <mesh geometry={nodes.Mesh083.geometry} material={materials.TX_Atlas8H_3} />
          <mesh geometry={nodes.Mesh083_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[39.567, -2.351, 74.267]} rotation={[1.582, -0.243, -1.525]} scale={0.3}>
          <mesh geometry={nodes.Mesh076.geometry} material={materials.TX_Atlas8H_2} />
          <mesh geometry={nodes.Mesh076_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[-10.622, 1.463, -23.529]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.2}>
          <mesh geometry={nodes.Mesh067.geometry} material={materials.TX_Atlas8H_1} />
          <mesh geometry={nodes.Mesh067_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[-15.437, -2.385, 58.996]} rotation={[1.334, 0, 0]} scale={0.3}>
          <mesh geometry={nodes.Mesh072.geometry} material={materials.TX_Atlas8H_2} />
          <mesh geometry={nodes.Mesh072_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[-29.902, -2.571, -22.337]} rotation={[1.497, 0.125, -0.992]} scale={0.2}>
          <mesh geometry={nodes.Mesh101.geometry} material={materials.TX_Atlas8H_1} />
          <mesh geometry={nodes.Mesh101_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[0.539, 5.136, 6.143]} rotation={[Math.PI / 2, 0, 0]} scale={0.25}>
          <mesh geometry={nodes.Mesh096.geometry} material={materials.TX_Atlas8H_1} />
          <mesh geometry={nodes.Mesh096_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[20.694, 1.4, -28.746]} rotation={[Math.PI / 2, 0, 0]} scale={0.3}>
          <mesh geometry={nodes.Mesh094.geometry} material={materials.TX_Atlas8H_4} />
          <mesh geometry={nodes.Mesh094_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[10.341, 1.553, -72.432]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.3}>
          <mesh geometry={nodes.Mesh087.geometry} material={materials.TX_Atlas8H_3} />
          <mesh geometry={nodes.Mesh087_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[-13.698, 1.015, -47.883]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.2}>
          <mesh geometry={nodes.Mesh089.geometry} material={materials.TX_Atlas8H_4} />
          <mesh geometry={nodes.Mesh089_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[22.825, -1.779, -2.806]} rotation={[Math.PI / 2, 0, 0]} scale={0.25}>
          <mesh geometry={nodes.Mesh082.geometry} material={materials.TX_Atlas8H_3} />
          <mesh geometry={nodes.Mesh082_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[35.958, -2.383, 61.682]} rotation={[1.333, -0.152, 0.558]} scale={0.3}>
          <mesh geometry={nodes.Mesh075.geometry} material={materials.TX_Atlas8H_2} />
          <mesh geometry={nodes.Mesh075_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[8.222, 1.765, 6.163]} rotation={[Math.PI / 2, 0, 0]} scale={0.25}>
          <mesh geometry={nodes.Mesh065.geometry} material={materials.TX_Atlas8H_1} />
          <mesh geometry={nodes.Mesh065_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[-30.616, -2.213, -3.726]} rotation={[Math.PI / 2, 0, 0.921]} scale={0.25}>
          <mesh geometry={nodes.Mesh100.geometry} material={materials.TX_Atlas8H_1} />
          <mesh geometry={nodes.Mesh100_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[20.764, 1.106, -8.622]} rotation={[Math.PI / 2, 0, 0]} scale={0.2}>
          <mesh geometry={nodes.Mesh093.geometry} material={materials.TX_Atlas8H_4} />
          <mesh geometry={nodes.Mesh093_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[0.78, 1.903, -83.874]} rotation={[Math.PI / 2, 0, 0]} scale={0.3}>
          <mesh geometry={nodes.Mesh086.geometry} material={materials.TX_Atlas8H_3} />
          <mesh geometry={nodes.Mesh086_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[-37.471, -2.367, 75.299]} rotation={[Math.PI / 2, 0.258, -Math.PI / 2]} scale={0.3}>
          <mesh geometry={nodes.Mesh079.geometry} material={materials.TX_Atlas8H_2} />
          <mesh geometry={nodes.Mesh079_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[0.429, -0.374, 75.9]} rotation={[1.766, 0, 0]} scale={0.65}>
          <mesh geometry={nodes.Mesh057.geometry} material={materials.TX_Atlas8H_1} />
          <mesh geometry={nodes.Mesh057_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[-17.893, 1.98, -65.186]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.3}>
          <mesh geometry={nodes.Mesh088.geometry} material={materials.TX_Atlas8H_4} />
          <mesh geometry={nodes.Mesh088_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[24.707, -0.816, 81.151]} rotation={[1.704, 0.104, 0.656]} scale={0.57}>
          <mesh geometry={nodes.Mesh059.geometry} material={materials.TX_Atlas8H_1} />
          <mesh geometry={nodes.Mesh059_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[-21.526, -1.654, -2.806]} rotation={[Math.PI / 2, 0, 0]} scale={0.25}>
          <mesh geometry={nodes.Mesh081.geometry} material={materials.TX_Atlas8H_3} />
          <mesh geometry={nodes.Mesh081_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[-26.598, -1.725, 85.545]} rotation={[-1.535, 0.065, 0.995]} scale={[-0.409, 0.409, 0.409]}>
          <mesh geometry={nodes.Mesh061.geometry} material={materials.TX_Atlas8H_1} />
          <mesh geometry={nodes.Mesh061_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[-34.548, -2.366, 61.333]} rotation={[1.388, 0.183, -0.778]} scale={0.3}>
          <mesh geometry={nodes.Mesh074.geometry} material={materials.TX_Atlas8H_2} />
          <mesh geometry={nodes.Mesh074_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[8.188, -2.758, -19.926]} rotation={[Math.PI / 2, 0, 0]} scale={0.2}>
          <mesh geometry={nodes.Mesh098.geometry} material={materials.TX_Atlas8H_1} />
          <mesh geometry={nodes.Mesh098_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[-7.068, 1.908, 6.144]} rotation={[Math.PI / 2, 0, 0]} scale={0.25}>
          <mesh geometry={nodes.Mesh063.geometry} material={materials.TX_Atlas8H_1} />
          <mesh geometry={nodes.Mesh063_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[-14.409, 0.153, 0.918]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.2}>
          <mesh geometry={nodes.Mesh091.geometry} material={materials.TX_Atlas8H_4} />
          <mesh geometry={nodes.Mesh091_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[-10.128, -2.101, -27.537]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.3}>
          <mesh geometry={nodes.Mesh099.geometry} material={materials.TX_Atlas8H_1} />
          <mesh geometry={nodes.Mesh099_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[13.157, -1.516, -52.709]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.25}>
          <mesh geometry={nodes.Mesh084.geometry} material={materials.TX_Atlas8H_3} />
          <mesh geometry={nodes.Mesh084_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[8.183, 1.983, 3.128]} rotation={[Math.PI / 2, 0, 0]} scale={0.25}>
          <mesh geometry={nodes.Mesh092.geometry} material={materials.TX_Atlas8H_4} />
          <mesh geometry={nodes.Mesh092_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[33.674, -1.31, 90.648]} rotation={[1.836, 0, Math.PI]} scale={0.5}>
          <mesh geometry={nodes.Mesh077.geometry} material={materials.TX_Atlas8H_2} />
          <mesh geometry={nodes.Mesh077_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[19.091, 1.4, -65.894]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.25}>
          <mesh geometry={nodes.Mesh085.geometry} material={materials.TX_Atlas8H_3} />
          <mesh geometry={nodes.Mesh085_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[14.819, 1.487, -11.707]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.2}>
          <mesh geometry={nodes.Mesh069.geometry} material={materials.TX_Atlas8H_1} />
          <mesh geometry={nodes.Mesh069_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[-32.785, -1.467, 91.244]} rotation={[2.035, 0, 0]} scale={0.5}>
          <mesh geometry={nodes.Mesh078.geometry} material={materials.TX_Atlas8H_2} />
          <mesh geometry={nodes.Mesh078_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[-4.749, -2.073, -66.118]} rotation={[Math.PI / 2, 0, 0]} scale={0.3}>
          <mesh geometry={nodes.Mesh102.geometry} material={materials.TX_Atlas8H_1} />
          <mesh geometry={nodes.Mesh102_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[0.438, 8.215, -66.577]} rotation={[Math.PI / 2, 0, 0]} scale={0.2}>
          <mesh geometry={nodes.Mesh071.geometry} material={materials.TX_Atlas8H_1} />
          <mesh geometry={nodes.Mesh071_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[-16.871, 1.024, -30.768]} rotation={[Math.PI / 2, 0, 0]} scale={0.3}>
          <mesh geometry={nodes.Mesh095.geometry} material={materials.TX_Atlas8H_4} />
          <mesh geometry={nodes.Mesh095_1.geometry} material={materials.TX_Frame1} />
        </group>
        <group position={[5.473, -2.08, -66.118]} rotation={[Math.PI / 2, 0, 0]} scale={0.3}>
          <mesh geometry={nodes.Mesh103.geometry} material={materials.TX_Atlas8H_1} />
          <mesh geometry={nodes.Mesh103_1.geometry} material={materials.TX_Frame1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/castillo/castle.gltf')
